
replicaCount: 2

# Refer to https://docs.livekit.io/deploy/kubernetes/ for instructions

livekit:
  rtc:
    use_external_ip: true
  redis:
    address: redis-cluster-ip-service:6379
  keys:
    qriosapikey: ""
  turn:
    enabled: true
    domain: turn.feenixtek.com
    tls_port: 3478
    secretName: qriosturnsslsecret
    udp_port: 443

loadBalancer:
  type: gke
  tls:
    - hosts:
        - streaam.feenixtek.com
      secretName: qriossslsecret

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# resources are set assuming a 8 core instance
resources:
#limits:
#cpu: 7500m
#memory: 2048Mi
#requests:
#cpu: 7000m
#memory: 1024Mi
